#!/usr/bin/env node

var Client = require('./client.js')
  , args = require('optimist').argv._
  , subscription
  , subscriptionArgs = args.slice(1);

function usage () {
   console.error('Connect to a DDP server');
   console.error('Usage: ddp connect');
   process.exit(1);
}

Client(function () {
  console.log('[connect]');
});
