#!/usr/bin/env node

var Client = require('./client.js')
  , args = require('optimist').argv._
  , subscription
  , subscriptionArgs = args.slice(1);

function usage () {
   console.error('Subscribe to a Meteor Collection');
   console.error('Usage: ddp subscribe <subscription> [<param1> <param2> ...]');
   process.exit(1);
}

if (!(subscription = args[0])) return usage();

Client(function () {
  console.log('[subscribe] ' + subscription);
  this.subscribe(subscription, subscriptionArgs);
});
