#!/usr/bin/env node

var Client = require('./client.js')
  , args = require('optimist').argv._
  , method
  , methodArgs = args.slice(1);

function usage () {
   console.error('Call a Meteor method');
   console.error('Usage: ddp call <method> [<param1> <param2> ...]');
   process.exit(1);
}

if (!(method = args[0])) return usage();

Client(function () {
  var client = this;
  methodArgs = this.parseArgs(methodArgs);
  console.log('[call]: ' + method + ' ' + JSON.stringify(methodArgs));
  this.call(method, methodArgs, function (err, res) {
    client.close();
    process.exit(0);
  });
});
