#!/usr/bin/env node

var Client = require('./client.js')
  , subscriptions = require('optimist').argv._

function usage () {
   console.error('Subscribe to multiple Meteor Collections');
   console.error('Usage: ddp subscribe-multi <subscription> [<subscription2> <subscription3> ...]');
   process.exit(1);
}

if (!subscriptions.length) return usage();

Client(function () {
  for (var i = 0; i < subscriptions.length; i++) {
    console.log('[subscribe] ' + subscriptions[i]);
    this.subscribe(subscriptions[i], []);
  }
});
