#!/bin/bash
echo "Installing ddp command line tools into /usr/local/bin"

function link {
  ln -sf "$PWD/$1" "/usr/local/bin/$1";
}

link "ddp"
link "ddp-call"
link "ddp-subscribe"
link "ddp-subscribe-multi"
link "ddp-connect"

echo "Install complete. Type this at the command prompt:"
echo "> ddp"
